# Generated by Django 3.2.3 on 2021-06-06 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='first_url',
            old_name='url',
            new_name='description_url',
        ),
        migrations.AddField(
            model_name='first_url',
            name='keywords_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='first_url',
            name='ogdescription_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
