# Generated by Django 3.2.3 on 2021-06-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0002_auto_20210606_0509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='first_url',
            options={'verbose_name_plural': 'first_url'},
        ),
    ]
